version: "3.8"

networks:
  video-storage-net:
    name: video-storage-net

services:
  application:
    container_name: video-storage-app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - video-storage-net
    links:
      - db
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      - POSTGRES_DB=videostore
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - video-storage-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
